# Generated by Django 4.1.1 on 2022-10-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawl',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='page',
            name='content_hash',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
