# Generated by Django 4.1.1 on 2022-10-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_crawler', '0002_alter_crawl_options_page_content_hash_alter_page_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='crawl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
